### ISSUE TITLE
some problem in main.py line254

### ISSUE THREAD

**Issue by chenjunyi1999** [devjwsong/gpt2-dialogue-generation-pytorch#10]
```python
token_type_ids = [start_sp_id] + list(chain.from_iterable(input_hists)) + [self.args.sp2_id]
```
Sorry but I cannot understand the parameters in the **chain.from_iterable( )**, i think it should be "token_type_ids" rather than "input_hists". Did I misunderstand your code here？

**Comment by devjwsong** [comment]
Thank you for your feedback!
And yes, I think you are right. I will update the code right now since it may cause quite a serious performance issue.
Thank you so much.

**Comment by devjwsong** [comment]
Pushed the fixed version.

**Comment by chenjunyi1999** [comment]
thanks for your reply and much appreciated for the code. learned a lot  as a NLP beginner. :)
